// Generated by CoffeeScript 1.6.3
(function() {
  var gen_content, gen_phrase, i, leading_zeroes, msg, phrase, phrases, random, seq, table, unique_words, wi, _i, _j, _len, _name, _ref,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    _this = this;

  msg = "приходи ёпта я тебя нахуй блядь ушатаю так что забудешь как тебя зовут понял\nхули ты блядь даёшь-то ишак ебаный\nебало закрыл своё\nя для тебя вообще не играю\nты чёрт ёпта галимый\nмне похуй можешь дома сидеть ёпта понял блядь\nещё раз напишете я вас там отпизжу всех нахуй понятно\nпидармотина ебаная\nвы болеть-то нихуя не умеете\nконченные блядь отродья\nдумаешь там пятьдесят человек у тебя пришло ты такой крутой\nхули ты блякаешь-то ёпта\nты вообще ебало закрой чтобы тебя не видно было понял нахуй\nздесь что ли хочешь остаться\nне для такого быдла как вот это\nкакого хуя ты туда вылетел-то ёпта мне интересно\nчто нет-то ёпта что нет\nвы чего быдлятина все блядь нахуй ёпта в одном стаде ёпта\nэто для тебя нормально а для меня нет ёпта\nс хуя это я должен футболку ему отдавать\nты мне объясни-ка блядь\nты за слова свои отвечаешь\nпетух ебаный нахуй";

  phrases = msg.split("\n").map(function(s) {
    return s.split(" ");
  });

  unique_words = [];

  phrases.forEach(function(p) {
    return p.reduce(function(r, w) {
      if (!(__indexOf.call(r, w) >= 0)) {
        r.push(w);
      }
      return r;
    }, unique_words);
  });

  table = {};

  for (_i = 0, _len = phrases.length; _i < _len; _i++) {
    phrase = phrases[_i];
    for (i = _j = 1, _ref = phrase.length; 1 <= _ref ? _j < _ref : _j > _ref; i = 1 <= _ref ? ++_j : --_j) {
      if (table[_name = phrase[i - 1]] == null) {
        table[_name] = [];
      }
      seq = table[phrase[i - 1]];
      wi = unique_words.indexOf(phrase[i]);
      if (!(__indexOf.call(seq, wi) >= 0)) {
        seq.push(wi);
      }
    }
  }

  random = function(to, from) {
    if (from == null) {
      from = 0;
    }
    return Math.min(to, Math.floor(Math.random() * (to - from)));
  };

  gen_phrase = function(len) {
    var cw, cwi;
    phrase = [];
    cwi = random(unique_words.length - 1);
    while (phrase.length < len) {
      cw = unique_words[cwi];
      phrase.push(cw);
      if (table[cw] != null) {
        cwi = table[cw][random(table[cw].length - 1)];
      } else {
        cwi = random(unique_words.length - 1);
      }
    }
    return phrase.join(" ");
  };

  leading_zeroes = function(n, len) {
    var s;
    if (len == null) {
      len = 2;
    }
    s = n.toString();
    while (s.length < len) {
      s = "0" + s;
    }
    return s;
  };

  gen_content = function() {
    phrase = gen_phrase(15);
    $("#txt").text(phrase);
    return $("#pic").attr("src", "roman/" + (leading_zeroes(random(31, 1))) + ".jpg");
  };

  $(gen_content);

}).call(this);
